server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

wutsi:
  client-id: checkout-manager
  application:
    name: checkout-manager
    jobs:
      pending-transaction:
        cron: "0 0 * * * *"  # Runs every hour
  platform:
    security:
      type: jwt
      public-endpoints:
        - "POST /v1/orders"
        - "GET /v1/orders/*"
        - "POST /v1/transactions/charges"
    cache:
      name: ${wutsi.application.name}
      type: local
    stream:
      name: ${wutsi.application.name}
      type: local
      subscriptions:
        - membership-manager
    tracing:
      client-id: ${wutsi.application.name}
      device-id-provider:
        type: header

logging:
  level:
    root: INFO
    com.wutsi.checkout.manager: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


