openapi: "3.0.0"
info:
  title: "Wutsi Checkout Manager API"
  description: Checkout Business Layer
  version: "1.0.0"

servers:
  - url: https://checkout-manager-test.herokuapp.com
    description: Sandbox
  - url: https://checkout-manager-prod.herokuapp.com
    description: Production

paths:
  /v1/payment-providers/search:
    post:
      operationId: "search-payment-provider"
      description: Search payment providers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchPaymentProviderRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchPaymentProviderResponse'
      tags:
        - Payment Method


  /v1/payment-methods:
    post:
      operationId: "add-payment-method"
      description: Add payment method to the current user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPaymentMethodRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddPaymentMethodResponse'
      tags:
        - Payment Method

  /v1/payment-methods/search:
    post:
      operationId: "search-payment-method"
      description: Search payment methods
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchPaymentMethodRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchPaymentMethodResponse'
      tags:
        - Payment Method

  /v1/payment-methods/{token}:
    get:
      operationId: "get-payment-method"
      description: Get a payment method
      parameters:
        - in: path
          name: token
          description: Payment method token
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPaymentMethodResponse'
        404:
          description: Payment method not found
      tags:
        - Payment Method


  /v1/businesses/{id}:
    get:
      operationId: "get-business"
      description: Return information of a business
      parameters:
        - in: path
          name: id
          description: ID of the business
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBusinessResponse'
        404:
          description: The business not found
      tags:
        - Business


  /v1/orders:
    post:
      operationId: "create-order"
      description: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderResponse'
      tags:
        - Order

  /v1/orders/{id}:
    get:
      operationId: "get-order"
      description: Get an order
      parameters:
        - in: path
          name: id
          description: ID of the order
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
      tags:
        - Order


  /v1/transactions/charge:
    post:
      operationId: "create-charge"
      description: Charge a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChargeRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChargeResponse'
      tags:
        - Transactions



components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    SearchPaymentProviderRequest:
      type: object
      properties:
        country:
          type: string
          description: Country code
          nullable: true
        number:
          type: string
          description: Phone or Bank account number
          nullable: true
        type:
          type: string
          description: Type of payment method
          enum:
            - MOBILE_MONEY
            - BANK
          nullable: true

    SearchPaymentProviderResponse:
      type: object
      properties:
        paymentProviders:
          type: array
          items:
            $ref: "#/components/schemas/PaymentProviderSummary"

    PaymentProviderSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the provider
        code:
          type: string
          description: Provider Code
        name:
          type: string
          description: Provider name
        type:
          type: string
          description: Type of payment method
          enum:
            - MOBILE_MONEY
            - BANK
        logoUrl:
          type: string
          format: url
          description: URL of the logo

    AddPaymentMethodRequest:
      type: object
      properties:
        providerId:
          type: integer
          format: int64
          description: ID of the payment provider
        type:
          type: string
          description: Type of payment method
          enum:
            - MOBILE_MONEY
            - BANK
        number:
          type: string
          description: Phone or Bank account number
          maxLength: 30
        country:
          type: string
          description: country 2 letter ISO code
          minLength: 2
          maxLength: 2
        ownerName:
          type: string
          description: Name of the owner of the payment method
          maxLength: 100
      required:
        - number
        - ownerName
        - type
        - country

    AddPaymentMethodResponse:
      type: object
      properties:
        paymentMethodToken:
          type: string
          format: uuid
          description: Payment method token

    GetPaymentMethodResponse:
      type: object
      properties:
        paymentMethod:
          type: object
          $ref: "#/components/schemas/PaymentMethod"

    GetPaymentMethodRequest:
      type: object
      properties:
        paymentMethod:
          type: object
          $ref: "#/components/schemas/PaymentMethod"

    SearchPaymentMethodRequest:
      type: object
      properties:
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
          nullable: true
          default: "ACTIVE"
        limit:
          type: integer
          default: 100
        offset:
          type: integer
          default: 0

    SearchPaymentMethodResponse:
      type: object
      properties:
        paymentMethods:
          type: array
          items:
            $ref: "#/components/schemas/PaymentMethodSummary"

    PaymentMethod:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          description: ID of the associated account
        token:
          type: string
          description: Payment Method's token
        type:
          type: string
          description: Type of payment method
        ownerName:
          type: string
          description: Name of the owner of the payment method
        number:
          type: string
          description: Payment method account number
        country:
          type: string
          description: country code - required for bank accounts
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        created:
          type: string
          format: date-time
          description: Creation date/time
        updated:
          type: string
          format: date-time
          description: Updated date/time
        deactivated:
          type: string
          format: date-time
          description: Date/time when the payment method was deactivated
          nullable: true
        provider:
          type: object
          $ref: "#/components/schemas/PaymentProviderSummary"

    PaymentMethodSummary:
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          description: ID of the associated account
        token:
          type: string
          description: Payment Method's token
        type:
          type: string
          description: Type of payment method
        number:
          type: string
          description: Payment method account number
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        created:
          type: string
          format: date-time
          description: Creation date/time
        updated:
          type: string
          format: date-time
          description: Updated date/time
        deactivated:
          type: string
          format: date-time
          description: Date/time when the payment method was deactivated
          nullable: true
        provider:
          type: object
          $ref: "#/components/schemas/PaymentProviderSummary"

    GetBusinessResponse:
      type: object
      properties:
        business:
          type: object
          $ref: "#/components/schemas/Business"

    Business:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the business
        accountId:
          type: integer
          format: int64
          description: ID of the associated account
        balance:
          type: integer
          format: int64
          description: Balance of the business
        country:
          type: string
          description: 2 letter country code
        currency:
          type: string
          description: 3 letter currency code
        status:
          type: string
          description: Status of the business
          enum:
            - UNDER_REVIEW
            - ACTIVE
            - SUSPENDED
        created:
          type: string
          format: date-time
          description: Registration Date/Time
        updated:
          type: string
          format: date-time
          description: Last modification Date/Time
        suspended:
          type: string
          format: date-time
          description: Suspension Date/Time
          nullable: true

    CreateOrderRequest:
      type: object
      properties:
        deviceType:
          type: string
          description: Type of the device
          nullable: true
        channelType:
          type: string
          description: Sales channel
          nullable: true
        businessId:
          type: integer
          format: int64
          description: ID of the store
        notes:
          type: string
          description: Customer Notes
          nullable: true
        customerId:
          type: integer
          format: int64
          description: Customer's account ID
          nullable: true
        customerName:
          type: string
          description: Customer's display name
        customerEmail:
          type: string
          description: Customer's email
          maxLength: 100
        items:
          type: array
          description: Items of order
          items:
            $ref: "#/components/schemas/CreateOrderItemRequest"
      required:
        - items
        - customerName
        - customerEmail

    CreateOrderItemRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product
        quantity:
          type: integer
          description: Number of offers

    CreateOrderResponse:
      type: object
      properties:
        orderId:
          type: string
          description: ID of the order
        orderStatus:
          type: string
          description: Status of the order

    CreateChargeRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Email of the customer
          maxLength: 100
        paymentMethodType:
          type: string
          description: Type of payment method
          nullable: true
        paymentMethodOwnerName:
          type: string
          description: Name of the payer
          nullable: true
          maxLength: 100
        paymentProviderId:
          type: integer
          format: int64
          description: ID of the payment provider
          nullable: true
        paymentMethodToken:
          type: string
          description: Payment token of the customer
          nullable: true
        paymenMethodNumber:
          type: string
          description: Payment method number
          nullable: true
          maxLength: 30
        businessId:
          type: integer
          format: int64
          description: ID of the business that will be creditted
        orderId:
          type: string
          description: ID of the order associated with the charge
        description:
          type: string
          description: Description of the transaction
          nullable: true
          maxLength: 100
        idempotencyKey:
          type: string
          description: Idemportent Key
          maxLength: 36
      required:
        - idempotencyKey
        - orderId
        - email

    CreateChargeResponse:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          description: ID of the transaction
        status:
          description: Status of the charge
          type: string
          enum:
            - PENDING
            - SUCESS

    GetOrderResponse:
      type: object
      properties:
        order:
          type: object
          $ref: "#/components/schemas/Order"

    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the order
        shortId:
          type: string
          description: Store version of the ID
        deviceId:
          type: string
          description: ID of the device
          nullable: true
        deviceType:
          type: string
          description: Type of the device
          nullable: true
        channelType:
          type: string
          description: Sales channel
          nullable: true
        businessId:
          type: integer
          format: int64
          description: ID of the merchant
        status:
          type: string
          description: Description of the order
          enum:
            - OPENED
            - CANCELLED
            - CLOSED
        subTotalPrice:
          type: integer
          format: int64
          description: Sub total price
        totalDiscount:
          type: integer
          format: int64
          description: Total Discount amount
        totalPrice:
          type: integer
          format: int64
          description: Total price
        totalPaid:
          type: integer
          format: int64
          description: Total amount paid by the customer
        balance:
          type: integer
          format: int64
          description: Balance to pay
        currency:
          type: string
          description: Currency
        created:
          type: string
          format: date-time
          description: Creation datetime
        updated:
          type: string
          format: date-time
          description: Last update
        cancelled:
          type: string
          format: date-time
          description: Cancellation date
          nullable: true
        cancellationReason:
          type: string
          nullable: true
        closed:
          type: string
          format: date-time
          description: Closed date
          nullable: true
        notes:
          type: string
          description: Note from customer
          nullable: true
        customerId:
          type: integer
          format: int64
          description: Customer's account ID
          nullable: true
        customerName:
          type: string
          description: Customer's display name
        customerEmail:
          type: string
          description: Customer's email
          maxLength: 100
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
        discounts:
          type: array
          items:
            $ref: "#/components/schemas/Discount"

    OrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product
        title:
          type: string
          description: Title of the product
        quantity:
          type: integer
          description: Number of offers
        pictureUrl:
          type: string
          format: url
          description: Offer picture URL
          nullable: true
        unitPrice:
          type: integer
          format: int64
          description: Unit price
        subTotalPrice:
          type: integer
          format: int64
          description: Sub total price
        totalDiscount:
          type: integer
          format: int64
          description: Total Discount amount
        totalPrice:
          type: integer
          format: int64
          description: Total price
        discounts:
          type: array
          items:
            $ref: "#/components/schemas/Discount"

    Discount:
      type: object
      properties:
        code:
          type: string
          description: Discount code
        amount:
          type: integer
          format: int64
          description: Discount amount
        rate:
          type: integer
          description: Discount rate (0 - 100)
        type:
          type: string
          description: Type of discount
